<?php defined('SYSPATH') OR die('No direct access allowed.');
/**
 * Default Kohana controller. This controller should NOT be used in production.
 * It is for demonstration purposes only!
 *
 * @package    Core
 * @author     Kohana Team
 * @copyright  (c) 2007-2008 Kohana Team
 * @license    http://kohanaphp.com/license.html
 */
class Welcome_Controller extends Template_Controller {

	const ALLOW_PRODUCTION = FALSE;

	public $template = 'kohana/template';


	public function login(){
		$this->template->title = 'Welcome to Kohana!';
		if(array_key_exists('submit', $_POST) and isset($_POST['submit'])){
			$cred = array();
			$cred['password'] = $_POST['password'];
			$cred['user_name'] = $_POST['user_name'];
			$user = Auth::instance()->login($cred);
			if(FALSE !== $user){
				echo $user->id;
				$this->template->content = "Sucess!";
			}else{
				$this->template->content = "Not A Sucess!";
			}
		}else{
			$this->template->content = new View('login');
		}
	}
	
	public function register(){
		$this->template->title = 'Welcome to Kohana!';
		if(array_key_exists('submit', $_POST) and isset($_POST['submit'])){
			$cred = array();

			$user_name = $_POST['user_name'];
			$email = $_POST['email'];
			$cred['password'] = $_POST['password'];
			$cred['password_confirm'] = $_POST['password_confirm'];
			$errors = Auth::instance()->register($user_name, $email, $cred);

			if(!count($errors)){
				$this->template->content = "Sucess!";
			}else{
				$this->template->content = "Not A Sucess!";
				foreach($errors as $f=>$error){
					$this->template->content .= "<br/>$f--$error";
				}
			}
		}else{
			$this->template->content = new View('register');
		}
	}

	public function index(){
		ORM::factory('ACL_Base');
		ORM::factory('ACL_User');

		ORM::factory('Item');
		ORM::factory('Text');
		ORM::factory('TTL_Sums');
		
		if(Auth::instance()->get_user()){
			echo Auth::instance()->get_user()->user_name;
		}else{
			echo "Not logged in";
		}
		echo "<br/><br/><br/>";
		ACL_User_Model::add_resource_for_entity(2,5,ACL_Base_Model::$READ);
		var_dump(ACL_User_Model::can_read(2, 5));
		var_dump(ACL_User_Model::can_write(2, 5));
		
		$b = new Text_Model();
		$b->text = "HI";
		$b->save();
		
		$i = new Item_Model();
		$i->body = $b;
		$i->save();
		echo "T:".$i->body->text;
		
		$b->text = "Ugh";
		$b->save();
		
		
		echo "T:".$i->body->text;
		
		$this->template->content = new View('welcome_content');

		$this->template->title = 'Welcome to Kohana!';

		$this->template->content->links = array
		(
			'Home Page'     => 'http://kohanaphp.com/',
			'Documentation' => 'http://docs.kohanaphp.com/',
			'Forum'         => 'http://forum.kohanaphp.com/',
			'License'       => 'Kohana License.html',
			'Donate'        => 'http://kohanaphp.com/donate',
		);
	}

	public function __call($method, $arguments){
		$this->auto_render = FALSE;

		echo 'This text is generated by __call. If you expected the index page, you need to use: welcome/index/'.substr(Router::$current_uri, 8);
	}

} // End Welcome Controller